# Site settings
title: North Carolina Illustrated
description: "Each piece of North Carolina’s new tax code tells a story, and we know how important it is to put that story into a larger context."
meta_image: cover-meta.jpg
url: "http://interactive.taxfoundation.org" # the base hostname & protocol for your site
baseurl: "/nc-illustrated"
permalink: :title
twitter_username: taxfoundation
# Setup and configure collection for chartbook slides
collections:
  - slides
# Build settings
markdown: kramdown
kramdown:
  input: GFM
